# -*- coding: utf-8 -*-
"""face recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ucp8rK_BGAe9QMia25aS7XI92hWCLBHZ
"""

!pip install face_recognition













